/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huerto.vista;

/**
 *
 * @author Fran
 */
public class AdministracionVista extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionVista
     */
    public AdministracionVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel0 = new javax.swing.JPanel();
        Panel1Up = new javax.swing.JPanel();
        UpPanel2Left = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        UpPanel2Right = new javax.swing.JPanel();
        ayuda = new javax.swing.JButton();
        UpPanel2Center = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        Panel1Center = new javax.swing.JPanel();
        Panel2Center = new javax.swing.JPanel();
        pnl1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnl9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboUsuarios = new javax.swing.JComboBox<>();
        pnl4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePar = new javax.swing.JTextField();
        pnl5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombrePer = new javax.swing.JTextField();
        pnl6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPassw = new javax.swing.JPasswordField();
        pnl3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnl7 = new javax.swing.JPanel();
        btnAplicar = new javax.swing.JButton();
        pnl10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnl11 = new javax.swing.JPanel();
        btnProductosEnBolsillos = new javax.swing.JButton();
        btnInfoJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel0.setLayout(new java.awt.BorderLayout());

        Panel1Up.setLayout(new java.awt.BorderLayout());

        UpPanel2Left.setBackground(new java.awt.Color(153, 255, 153));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setText("<");
        btnBack.setActionCommand("back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        UpPanel2Left.add(btnBack);

        Panel1Up.add(UpPanel2Left, java.awt.BorderLayout.LINE_START);

        UpPanel2Right.setBackground(new java.awt.Color(153, 255, 153));

        ayuda.setText("Ayuda");
        ayuda.setActionCommand("help");
        UpPanel2Right.add(ayuda);

        Panel1Up.add(UpPanel2Right, java.awt.BorderLayout.LINE_END);

        UpPanel2Center.setBackground(new java.awt.Color(153, 255, 153));

        imgLogo.setText("Logo APP");
        UpPanel2Center.add(imgLogo);

        Panel1Up.add(UpPanel2Center, java.awt.BorderLayout.CENTER);

        jPanel0.add(Panel1Up, java.awt.BorderLayout.PAGE_START);

        Panel1Center.setLayout(new java.awt.BorderLayout());

        Panel2Center.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel2Center.setLayout(new javax.swing.BoxLayout(Panel2Center, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PANEL DE ADMINISTRACIÓN");
        pnl1.add(jLabel1);

        Panel2Center.add(pnl1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" En esta ventana se podrán modificar los siguientes parámetros: nombres de partidas, nombres de personajes, contraseñas y el dinero de cada jugador.");
        jLabel8.setPreferredSize(new java.awt.Dimension(800, 50));
        pnl8.add(jLabel8);

        Panel2Center.add(pnl8);

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Si un campo no tiene nada escrito, no se actualizará su valor.");
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(800, 50));
        pnl9.add(jLabel9);

        Panel2Center.add(pnl9);

        jLabel3.setText("Usuario al que se le aplicarán cambios");
        pnl2.add(jLabel3);

        comboUsuarios.setActionCommand("combo");
        pnl2.add(comboUsuarios);

        Panel2Center.add(pnl2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre de la partida");
        pnl4.add(jLabel5);

        txtNombrePar.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl4.add(txtNombrePar);

        Panel2Center.add(pnl4);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre del personaje");
        pnl5.add(jLabel6);

        txtNombrePer.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl5.add(txtNombrePer);

        Panel2Center.add(pnl5);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contraseña");
        pnl6.add(jLabel7);

        txtPassw.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl6.add(txtPassw);

        Panel2Center.add(pnl6);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dinero");
        pnl3.add(jLabel2);

        txtDinero.setBackground(new java.awt.Color(0, 0, 0));
        txtDinero.setForeground(new java.awt.Color(255, 255, 51));
        txtDinero.setPreferredSize(new java.awt.Dimension(75, 20));
        pnl3.add(txtDinero);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("€");
        jLabel4.setOpaque(true);
        pnl3.add(jLabel4);

        Panel2Center.add(pnl3);

        pnl7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAplicar.setText("Aplicar cambios");
        btnAplicar.setActionCommand("aplicar");
        pnl7.add(btnAplicar);

        Panel2Center.add(pnl7);

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Informes. Cuando se muestren, se guardarán en pdf en la raíz del proyecto.");
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(800, 50));
        pnl10.add(jLabel10);

        Panel2Center.add(pnl10);

        btnProductosEnBolsillos.setText("Productos en bolsillos");
        btnProductosEnBolsillos.setActionCommand("bolsillos");
        pnl11.add(btnProductosEnBolsillos);

        btnInfoJugador.setText("Información de una partida");
        btnInfoJugador.setActionCommand("partidas");
        pnl11.add(btnInfoJugador);

        Panel2Center.add(pnl11);

        Panel1Center.add(Panel2Center, java.awt.BorderLayout.CENTER);

        jPanel0.add(Panel1Center, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel0, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1Center;
    private javax.swing.JPanel Panel1Up;
    private javax.swing.JPanel Panel2Center;
    private javax.swing.JPanel UpPanel2Center;
    private javax.swing.JPanel UpPanel2Left;
    private javax.swing.JPanel UpPanel2Right;
    public javax.swing.JButton ayuda;
    public javax.swing.JButton btnAplicar;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnInfoJugador;
    public javax.swing.JButton btnProductosEnBolsillos;
    public javax.swing.JComboBox<String> comboUsuarios;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel0;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl10;
    private javax.swing.JPanel pnl11;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnl8;
    private javax.swing.JPanel pnl9;
    public javax.swing.JTextField txtDinero;
    public javax.swing.JTextField txtNombrePar;
    public javax.swing.JTextField txtNombrePer;
    public javax.swing.JPasswordField txtPassw;
    // End of variables declaration//GEN-END:variables
}
