/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huerto.vista;

/**
 *
 * @author Fran
 */
public class PartidasVista extends javax.swing.JFrame {

    /**
     * Creates new form VistaPartidas
     */
    public PartidasVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel0 = new javax.swing.JPanel();
        Panel1Left = new javax.swing.JPanel();
        Panel21 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        Panel22 = new javax.swing.JPanel();
        btnContinue = new javax.swing.JButton();
        Panel24 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        Panel1Up = new javax.swing.JPanel();
        UpPanel2Left = new javax.swing.JPanel();
        UpPanel2Right = new javax.swing.JPanel();
        ayuda = new javax.swing.JButton();
        UpPanel2Center = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        Panel1Center = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(850, 480));

        Panel0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 0), 2, true));
        Panel0.setLayout(new java.awt.BorderLayout());

        Panel1Left.setBackground(new java.awt.Color(204, 255, 204));
        Panel1Left.setLayout(new javax.swing.BoxLayout(Panel1Left, javax.swing.BoxLayout.Y_AXIS));

        Panel21.setBackground(new java.awt.Color(204, 255, 204));

        btnNew.setText("Nueva partida");
        btnNew.setActionCommand("new");
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setPreferredSize(new java.awt.Dimension(150, 50));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        Panel21.add(btnNew);

        Panel1Left.add(Panel21);

        Panel22.setBackground(new java.awt.Color(204, 255, 204));

        btnContinue.setText("Continuar");
        btnContinue.setActionCommand("continue");
        btnContinue.setPreferredSize(new java.awt.Dimension(150, 50));
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        Panel22.add(btnContinue);

        Panel1Left.add(Panel22);

        Panel24.setBackground(new java.awt.Color(204, 255, 204));

        btnSalir.setText("Salir");
        btnSalir.setActionCommand("exit");
        btnSalir.setPreferredSize(new java.awt.Dimension(150, 50));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        Panel24.add(btnSalir);

        Panel1Left.add(Panel24);

        Panel0.add(Panel1Left, java.awt.BorderLayout.LINE_START);

        Panel1Up.setBackground(new java.awt.Color(204, 255, 204));
        Panel1Up.setLayout(new java.awt.BorderLayout());

        UpPanel2Left.setBackground(new java.awt.Color(153, 255, 153));
        Panel1Up.add(UpPanel2Left, java.awt.BorderLayout.LINE_START);

        UpPanel2Right.setBackground(new java.awt.Color(153, 255, 153));

        ayuda.setText("Ayuda");
        ayuda.setActionCommand("help");
        UpPanel2Right.add(ayuda);

        Panel1Up.add(UpPanel2Right, java.awt.BorderLayout.LINE_END);

        UpPanel2Center.setBackground(new java.awt.Color(153, 255, 153));

        imgLogo.setText("Logo APP");
        UpPanel2Center.add(imgLogo);

        Panel1Up.add(UpPanel2Center, java.awt.BorderLayout.CENTER);

        Panel0.add(Panel1Up, java.awt.BorderLayout.PAGE_START);

        Panel1Center.setLayout(new java.awt.BorderLayout());

        tabla.setBackground(new java.awt.Color(204, 255, 204));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        Panel1Center.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel0.add(Panel1Center, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panel0, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel0;
    private javax.swing.JPanel Panel1Center;
    public javax.swing.JPanel Panel1Left;
    private javax.swing.JPanel Panel1Up;
    private javax.swing.JPanel Panel21;
    private javax.swing.JPanel Panel22;
    private javax.swing.JPanel Panel24;
    private javax.swing.JPanel UpPanel2Center;
    private javax.swing.JPanel UpPanel2Left;
    private javax.swing.JPanel UpPanel2Right;
    public javax.swing.JButton ayuda;
    public javax.swing.JButton btnContinue;
    public javax.swing.JButton btnNew;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
