/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huerto.vista;

/**
 *
 * @author Fran
 */
public class HuertoVista extends javax.swing.JFrame {

    /**
     * Creates new form HuertoVista
     */
    public HuertoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel0 = new javax.swing.JPanel();
        Panel1Down = new javax.swing.JPanel();
        Objetos = new javax.swing.JPanel();
        itemUndo = new javax.swing.JButton();
        item1 = new javax.swing.JToggleButton();
        item2 = new javax.swing.JToggleButton();
        item3 = new javax.swing.JToggleButton();
        item4 = new javax.swing.JToggleButton();
        item5 = new javax.swing.JToggleButton();
        item6 = new javax.swing.JToggleButton();
        item7 = new javax.swing.JToggleButton();
        item8 = new javax.swing.JToggleButton();
        item9 = new javax.swing.JToggleButton();
        item10 = new javax.swing.JToggleButton();
        itemNext = new javax.swing.JButton();
        Panel1Up = new javax.swing.JPanel();
        UpPanel2Left = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        UpPanel2Right = new javax.swing.JPanel();
        ayuda = new javax.swing.JButton();
        UpPanel2Center = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        Panel1Center = new javax.swing.JPanel();
        Panel2Center = new javax.swing.JPanel();
        SeparaInfo = new javax.swing.JPanel();
        PBox2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barEnergia = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        barAgua = new javax.swing.JProgressBar();
        PBox3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        relojHuerto = new relojhuerto.RelojHuerto();
        jLabel4 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNombreHuerto = new javax.swing.JLabel();
        lblDinero = new javax.swing.JLabel();
        PBox1 = new javax.swing.JPanel();
        PanelUpHuerto = new javax.swing.JPanel();
        btnObjeto = new javax.swing.JButton();
        btnAddParcela = new javax.swing.JButton();
        comboParcelas = new javax.swing.JComboBox<>();
        btnEntrarAdmin = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        PanelLeftHuerto = new javax.swing.JPanel();
        PanelDescObj1 = new javax.swing.JPanel();
        DescObj11 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        DescObj12 = new javax.swing.JPanel();
        lblDescNombre = new javax.swing.JLabel();
        PanelDescObj2 = new javax.swing.JPanel();
        DescObj21 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        DescObj22 = new javax.swing.JPanel();
        lblDescDesc = new javax.swing.JLabel();
        PanelDescObj3 = new javax.swing.JPanel();
        DescObj23 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        DescObj24 = new javax.swing.JPanel();
        lblDescFase = new javax.swing.JLabel();
        PanelDescObj4 = new javax.swing.JPanel();
        DescObj25 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        DescObj26 = new javax.swing.JPanel();
        btnRegar = new javax.swing.JButton();
        btnTirar = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnAddTienda = new javax.swing.JButton();
        PanelRightHuerto = new javax.swing.JPanel();
        btnTienda = new javax.swing.JButton();
        btnBorrarPartida = new javax.swing.JButton();
        PanelGrid = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 500));

        jPanel0.setLayout(new java.awt.BorderLayout());

        Panel1Down.setLayout(new javax.swing.BoxLayout(Panel1Down, javax.swing.BoxLayout.X_AXIS));

        Objetos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        itemUndo.setText("<<");
        itemUndo.setActionCommand("itemundo");
        itemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUndoActionPerformed(evt);
            }
        });
        Objetos.add(itemUndo);

        item1.setActionCommand("item1");
        item1.setOpaque(true);
        Objetos.add(item1);

        item2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/girasol.png"))); // NOI18N
        item2.setActionCommand("item2");
        item2.setOpaque(true);
        Objetos.add(item2);

        item3.setActionCommand("item3");
        item3.setOpaque(true);
        Objetos.add(item3);

        item4.setActionCommand("item4");
        item4.setOpaque(true);
        Objetos.add(item4);

        item5.setActionCommand("item5");
        item5.setOpaque(true);
        Objetos.add(item5);

        item6.setActionCommand("item6");
        item6.setOpaque(true);
        Objetos.add(item6);

        item7.setActionCommand("item7");
        item7.setOpaque(true);
        Objetos.add(item7);

        item8.setActionCommand("item8");
        item8.setOpaque(true);
        Objetos.add(item8);

        item9.setActionCommand("item9");
        item9.setOpaque(true);
        Objetos.add(item9);

        item10.setActionCommand("item10");
        item10.setOpaque(true);
        Objetos.add(item10);

        itemNext.setText(">>");
        itemNext.setActionCommand("itemnext");
        itemNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNextActionPerformed(evt);
            }
        });
        Objetos.add(itemNext);

        Panel1Down.add(Objetos);

        jPanel0.add(Panel1Down, java.awt.BorderLayout.PAGE_END);

        Panel1Up.setLayout(new java.awt.BorderLayout());

        UpPanel2Left.setBackground(new java.awt.Color(153, 255, 153));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setText("<");
        btnBack.setActionCommand("back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        UpPanel2Left.add(btnBack);

        Panel1Up.add(UpPanel2Left, java.awt.BorderLayout.LINE_START);

        UpPanel2Right.setBackground(new java.awt.Color(153, 255, 153));

        ayuda.setText("Ayuda");
        ayuda.setActionCommand("help");
        UpPanel2Right.add(ayuda);

        Panel1Up.add(UpPanel2Right, java.awt.BorderLayout.LINE_END);

        UpPanel2Center.setBackground(new java.awt.Color(153, 255, 153));

        imgLogo.setText("Logo APP");
        imgLogo.setToolTipText("");
        UpPanel2Center.add(imgLogo);

        Panel1Up.add(UpPanel2Center, java.awt.BorderLayout.CENTER);

        jPanel0.add(Panel1Up, java.awt.BorderLayout.PAGE_START);

        Panel1Center.setLayout(new java.awt.BorderLayout());

        Panel2Center.setLayout(new javax.swing.BoxLayout(Panel2Center, javax.swing.BoxLayout.Y_AXIS));

        SeparaInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SeparaInfo.setLayout(new javax.swing.BoxLayout(SeparaInfo, javax.swing.BoxLayout.X_AXIS));

        PBox2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Energía");
        PBox2.add(jLabel1);

        barEnergia.setBackground(new java.awt.Color(255, 255, 255));
        barEnergia.setForeground(new java.awt.Color(0, 204, 0));
        PBox2.add(barEnergia);

        jLabel2.setText("Agua");
        PBox2.add(jLabel2);

        barAgua.setBackground(new java.awt.Color(255, 255, 255));
        barAgua.setForeground(new java.awt.Color(0, 153, 153));
        barAgua.setValue(100);
        PBox2.add(barAgua);

        SeparaInfo.add(PBox2);

        PBox3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setText("HORA");
        PBox3.add(jLabel3);

        relojHuerto.setHora(new relojhuerto.Hora(8));
        PBox3.add(relojHuerto);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setText("FECHA");
        PBox3.add(jLabel4);

        lblFecha.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("fecha");
        PBox3.add(lblFecha);

        lblNombreHuerto.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lblNombreHuerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreHuerto.setText("xxxxxxxxx");
        PBox3.add(lblNombreHuerto);

        lblDinero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDinero.setForeground(new java.awt.Color(204, 204, 0));
        lblDinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDinero.setText("1000 $");
        PBox3.add(lblDinero);

        SeparaInfo.add(PBox3);

        Panel2Center.add(SeparaInfo);

        PBox1.setLayout(new java.awt.BorderLayout());

        PanelUpHuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnObjeto.setText("Coger producto para plantar aleatorio");
        btnObjeto.setActionCommand("girasol");
        PanelUpHuerto.add(btnObjeto);

        btnAddParcela.setText("Añadir Parcela");
        btnAddParcela.setActionCommand("newparcela");
        PanelUpHuerto.add(btnAddParcela);

        PanelUpHuerto.add(comboParcelas);

        btnEntrarAdmin.setText("ENTRAR");
        btnEntrarAdmin.setActionCommand("entrarParcela");
        PanelUpHuerto.add(btnEntrarAdmin);

        btnAdministrar.setBackground(new java.awt.Color(255, 153, 153));
        btnAdministrar.setText("PANEL DE ADMINISTRACIÓN");
        btnAdministrar.setActionCommand("administrar");
        PanelUpHuerto.add(btnAdministrar);

        PBox1.add(PanelUpHuerto, java.awt.BorderLayout.PAGE_START);

        PanelLeftHuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelLeftHuerto.setLayout(new javax.swing.BoxLayout(PanelLeftHuerto, javax.swing.BoxLayout.Y_AXIS));

        PanelDescObj1.setLayout(new javax.swing.BoxLayout(PanelDescObj1, javax.swing.BoxLayout.Y_AXIS));

        DescObj11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setText("Nombre");
        DescObj11.add(jLabel65);

        PanelDescObj1.add(DescObj11);

        lblDescNombre.setText("Selecciona una parcela");
        DescObj12.add(lblDescNombre);

        PanelDescObj1.add(DescObj12);

        PanelLeftHuerto.add(PanelDescObj1);

        PanelDescObj2.setLayout(new javax.swing.BoxLayout(PanelDescObj2, javax.swing.BoxLayout.Y_AXIS));

        DescObj21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel66.setText("Descripción");
        DescObj21.add(jLabel66);

        PanelDescObj2.add(DescObj21);

        lblDescDesc.setText("Selecciona una parcela");
        DescObj22.add(lblDescDesc);

        PanelDescObj2.add(DescObj22);

        PanelLeftHuerto.add(PanelDescObj2);

        PanelDescObj3.setLayout(new javax.swing.BoxLayout(PanelDescObj3, javax.swing.BoxLayout.Y_AXIS));

        DescObj23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel67.setText("Fase");
        DescObj23.add(jLabel67);

        PanelDescObj3.add(DescObj23);

        lblDescFase.setText("Selecciona una parcela");
        DescObj24.add(lblDescFase);

        PanelDescObj3.add(DescObj24);

        PanelLeftHuerto.add(PanelDescObj3);

        PanelDescObj4.setLayout(new javax.swing.BoxLayout(PanelDescObj4, javax.swing.BoxLayout.Y_AXIS));

        DescObj25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel68.setText("Acciones");
        DescObj25.add(jLabel68);

        PanelDescObj4.add(DescObj25);

        btnRegar.setBackground(new java.awt.Color(204, 255, 255));
        btnRegar.setText("Regar");
        btnRegar.setActionCommand("regar");
        btnRegar.setEnabled(false);
        DescObj26.add(btnRegar);

        btnTirar.setBackground(new java.awt.Color(255, 204, 204));
        btnTirar.setText("Tirar");
        btnTirar.setActionCommand("tirar");
        btnTirar.setEnabled(false);
        DescObj26.add(btnTirar);

        btnVender.setBackground(new java.awt.Color(255, 255, 204));
        btnVender.setText("Vender");
        btnVender.setActionCommand("vender");
        btnVender.setEnabled(false);
        DescObj26.add(btnVender);

        btnAddTienda.setText("Añadir a la tienda");
        btnAddTienda.setActionCommand("addShop");
        DescObj26.add(btnAddTienda);

        PanelDescObj4.add(DescObj26);

        PanelLeftHuerto.add(PanelDescObj4);

        PBox1.add(PanelLeftHuerto, java.awt.BorderLayout.LINE_START);

        PanelRightHuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelRightHuerto.setLayout(new javax.swing.BoxLayout(PanelRightHuerto, javax.swing.BoxLayout.Y_AXIS));

        btnTienda.setText("Ir al mercado");
        btnTienda.setActionCommand("shop");
        PanelRightHuerto.add(btnTienda);

        btnBorrarPartida.setText("Borrar partida");
        btnBorrarPartida.setActionCommand("erase");
        PanelRightHuerto.add(btnBorrarPartida);

        PBox1.add(PanelRightHuerto, java.awt.BorderLayout.LINE_END);

        PanelGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelGrid.setLayout(new java.awt.GridLayout(1, 1));
        PBox1.add(PanelGrid, java.awt.BorderLayout.CENTER);

        Panel2Center.add(PBox1);

        Panel1Center.add(Panel2Center, java.awt.BorderLayout.CENTER);

        jPanel0.add(Panel1Center, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel0, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void itemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUndoActionPerformed

    private void itemNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DescObj11;
    private javax.swing.JPanel DescObj12;
    private javax.swing.JPanel DescObj21;
    private javax.swing.JPanel DescObj22;
    private javax.swing.JPanel DescObj23;
    private javax.swing.JPanel DescObj24;
    private javax.swing.JPanel DescObj25;
    private javax.swing.JPanel DescObj26;
    private javax.swing.JPanel Objetos;
    private javax.swing.JPanel PBox1;
    private javax.swing.JPanel PBox2;
    private javax.swing.JPanel PBox3;
    private javax.swing.JPanel Panel1Center;
    private javax.swing.JPanel Panel1Down;
    private javax.swing.JPanel Panel1Up;
    private javax.swing.JPanel Panel2Center;
    private javax.swing.JPanel PanelDescObj1;
    private javax.swing.JPanel PanelDescObj2;
    private javax.swing.JPanel PanelDescObj3;
    private javax.swing.JPanel PanelDescObj4;
    public javax.swing.JPanel PanelGrid;
    private javax.swing.JPanel PanelLeftHuerto;
    private javax.swing.JPanel PanelRightHuerto;
    public javax.swing.JPanel PanelUpHuerto;
    private javax.swing.JPanel SeparaInfo;
    private javax.swing.JPanel UpPanel2Center;
    private javax.swing.JPanel UpPanel2Left;
    private javax.swing.JPanel UpPanel2Right;
    public javax.swing.JButton ayuda;
    public javax.swing.JProgressBar barAgua;
    public javax.swing.JProgressBar barEnergia;
    public javax.swing.JButton btnAddParcela;
    public javax.swing.JButton btnAddTienda;
    public javax.swing.JButton btnAdministrar;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnBorrarPartida;
    public javax.swing.JButton btnEntrarAdmin;
    public javax.swing.JButton btnObjeto;
    public javax.swing.JButton btnRegar;
    public javax.swing.JButton btnTienda;
    public javax.swing.JButton btnTirar;
    public javax.swing.JButton btnVender;
    public javax.swing.JComboBox<String> comboParcelas;
    private javax.swing.JLabel imgLogo;
    public javax.swing.JToggleButton item1;
    public javax.swing.JToggleButton item10;
    public javax.swing.JToggleButton item2;
    public javax.swing.JToggleButton item3;
    public javax.swing.JToggleButton item4;
    public javax.swing.JToggleButton item5;
    public javax.swing.JToggleButton item6;
    public javax.swing.JToggleButton item7;
    public javax.swing.JToggleButton item8;
    public javax.swing.JToggleButton item9;
    public javax.swing.JButton itemNext;
    public javax.swing.JButton itemUndo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel0;
    public javax.swing.JLabel lblDescDesc;
    public javax.swing.JLabel lblDescFase;
    public javax.swing.JLabel lblDescNombre;
    public javax.swing.JLabel lblDinero;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblNombreHuerto;
    public relojhuerto.RelojHuerto relojHuerto;
    // End of variables declaration//GEN-END:variables
}
